// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLogHighlightConfiguration() {
  return window['go']['main']['App']['GetLogHighlightConfiguration']();
}

export function GetLogOverview() {
  return window['go']['main']['App']['GetLogOverview']();
}

export function ListLogs(arg1) {
  return window['go']['main']['App']['ListLogs'](arg1);
}

export function SaveLogHighlightSettings(arg1) {
  return window['go']['main']['App']['SaveLogHighlightSettings'](arg1);
}
