// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {logs} from '../models';

export function GetLogOverview():Promise<logs.LogOverview>;

export function ListLogs(arg1:logs.ListLogsRequest):Promise<logs.LogPage>;
