// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {logs} from '../models';

export function GetLogHighlightConfiguration():Promise<Array<logs.ApplicationHighlight>>;

export function GetLogOverview():Promise<logs.LogOverview>;

export function ListLogs(arg1:logs.ListLogsRequest):Promise<logs.LogPage>;

export function SaveLogHighlightSettings(arg1:Array<logs.HighlightSetting>):Promise<void>;
